Imported Upstream version 4.4.7

diff --git a/shorewall6 b/shorewall6
--- a/shorewall6
+++ b/shorewall6
@@ -220,6 +220,20 @@ get_config() {
 	    fi
 	    ;;
     esac
+
+    case $LOAD_HELPERS_ONLY in
+	Yes|yes)
+	    ;;
+	No|no)
+	    LOAD_HELPERS_ONLY=
+	    ;;
+	*)
+	    if [ -n "$LOAD_HELPERS_ONLY" ]; then
+		echo "   ERROR: Invalid LOAD_HELPERS_ONLY setting ($LOAD_HELPERS_ONLY)" >&2
+		exit 1
+	    fi
+	    ;;
+    esac
 }
 
 #
@@ -1330,6 +1344,7 @@ VERBOSE_OFFSET=0
 USE_VERBOSITY=
 NOROUTES=
 PURGE=
+DEBUG=
 EXPORT=
 export TIMESTAMP=
 noroutes=
