Imported Upstream version 4.4.20

diff --git a/shorewall6 b/shorewall6
--- a/shorewall6
+++ b/shorewall6
@@ -1,10 +1,11 @@
 #!/bin/sh
 #
-#     Shorewall Packet Filtering Firewall Control Program - V4.2
+#     Shorewall Packet Filtering Firewall Control Program - V4.4
 #
 #     This program is under GPL [http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt]
 #
-#     (c) 1999,2000,2001,2002,2003,2004,2005,2006,2007,2008 - Tom Eastep (teastep@shorewall.net)
+#     (c) 1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011 - 
+#         Tom Eastep (teastep@shorewall.net)
 #
 #	This file should be placed in /sbin/shorewall6.
 #
@@ -32,9 +33,9 @@
 #     $1 = Yes: read the params file
 #     $2 = Yes: check for STARTUP_ENABLED
 #     $3 = Yes: Check for LOGFILE
-#     
 #
 get_config() {
+    local prog
 
     ensure_config_path
 
@@ -47,7 +48,7 @@ get_config() {
     fi
 
     config=$(find_file shorewall6.conf)
-    
+
     if [ -f $config ]; then
 	if [ -r $config ]; then
 	    . $config
@@ -61,7 +62,7 @@ get_config() {
     fi
 
     ensure_config_path
-    
+
     if [ -z "$g_export" -a "$(id -u)" = 0 ]; then
 	#
 	# This block is avoided for compile for export and when the user isn't root
@@ -92,6 +93,68 @@ get_config() {
 	    fi
 	fi
 
+	if [ -n "$IP" ]; then
+	    case "$IP" in
+		*/*)
+		    if [ ! -x "$IP" ] ; then
+			echo "   ERROR: The program specified in IP ($IP) does not exist or is not executable" >&2
+			exit 2
+		    fi
+		    ;;
+		*)
+		    prog="$(mywhich $IP 2> /dev/null)"
+		    if [ -z "$prog" ] ; then
+			echo "   ERROR: Can't find $IP executable" >&2
+			exit 2
+		    fi
+		    IP=$prog
+		    ;;
+	    esac
+	else
+	    IP='ip'
+	fi
+
+	if [ -n "$IPSET" ]; then
+	    case "$IPSET" in
+		*/*)
+		    if [ ! -x "$IPSET" ] ; then
+			echo "   ERROR: The program specified in IPSET ($IPSET) does not exist or is not executable" >&2
+			exit 2
+		    fi
+		    ;;
+		*)
+		    prog="$(mywhich $IPSET 2> /dev/null)"
+		    if [ -z "$prog" ] ; then
+			echo "   ERROR: Can't find $IPSET executable" >&2
+			exit 2
+		    fi
+		    IPSET=$prog
+		    ;;
+	    esac
+	else
+	    IPSET='ipset'
+	fi
+
+	if [ -n "$TC" ]; then
+	    case "$TC" in
+		*/*)
+		    if [ ! -x "$TC" ] ; then
+			echo "   ERROR: The program specified in TC ($TC) does not exist or is not executable" >&2
+			exit 2
+		    fi
+		    ;;
+		*)
+		    prog="$(mywhich $TC 2> /dev/null)"
+		    if [ -z "$prog" ] ; then
+			echo "   ERROR: Can't find $TC executable" >&2
+			exit 2
+		    fi
+		    TC=$prog
+		    ;;
+	    esac
+	else
+	    TC='tc'
+	fi
 	#
 	# Compile by non-root needs no restore file
 	#
@@ -116,13 +179,25 @@ get_config() {
 	    esac
 	fi
 
+	case ${SHOREWALL_COMPILER:=perl} in
+	    perl|Perl)
+		;;
+	    shell|Shell)
+		echo "   WARNING: SHOREWALL_COMPILER=shell ignored. Shorewall-shell support has been removed in this release" >&2
+		;;
+	    *)
+		echo "   ERROR: Invalid value ($SHOREWALL_COMPILER) for SHOREWALL_COMPILER" >&2
+		exit 2
+		;;
+	esac
+
 	case ${TC_ENABLED:=Internal} in
 	    No|NO|no)
 	        TC_ENABLED=
 		;;
 	esac
 
-	[ -n "$LOGFORMAT" ] || LOGFORMAT='Shorewall6:%s.%s'
+	[ -z "$LOGFORMAT" ] && LOGFORMAT='Shorewall:%s.%s'
 
 	[ -n "$LOGFORMAT" ] && LOGFORMAT="${LOGFORMAT%%%*}"
 
@@ -148,7 +223,7 @@ get_config() {
     else
 	STARTUP_LOG=
 	LOG_VERBOSITY=-1
-    fi   
+    fi
 
     if [ -n "$SHOREWALL_SHELL" ]; then
 	if [ ! -x "$SHOREWALL_SHELL" ]; then
@@ -224,6 +299,22 @@ get_config() {
 	    fi
 	    ;;
     esac
+
+    case $LEGACY_FASTSTART in
+	Yes|yes)
+	    ;;
+	No|no)
+	    LEGACY_FASTSTART=
+	    ;;
+	*)
+	    if [ -n "$LEGACY_FASTSTART" ]; then
+		echo "   ERROR: Invalid LEGACY_FASTSTART setting ($LEGACY_FASTSTART)" >&2
+		exit 1
+	    fi
+
+	    LEGACY_FASTSTART=Yes
+	    ;;
+    esac
 }
 
 #
@@ -234,18 +325,21 @@ startup_error() {
     kill $$
     exit 1
 }
-    
+
 #
-# Run the appropriate compiler
+# Determine if there are config files newer than the passed object
+#
+uptodate() {
+    [ -f $1 ] && [ -z "$(find ${CONFDIR} -newer $1)" ]
+}
+
+#
+# Run the compiler
 #
 compiler() {
-    pc=/usr/$g_libexec/shorewall/compiler.pl
+    local pc
+    pc=$g_libexec/shorewall/compiler.pl
 
-    local command
-    command=$1
-
-    shift
-    
     if [ $(id -u) -ne 0 ]; then
 	if [ -z "$SHOREWALL_DIR" -o "$SHOREWALL_DIR" = /etc/shorewall6 ]; then
 	    startup_error "Ordinary users may not compile the /etc/shorewall6 configuration"
@@ -256,8 +350,6 @@ compiler() {
     #
     ensure_config_path
 
-    haveparams=
-
     case $COMMAND in
 	*start|try|refresh)
 	    ;;
@@ -267,17 +359,15 @@ compiler() {
 	    ;;
     esac
 
-    [ $command = exec ] || command=
-    
     debugflags="-w"
     [ -n "$g_debug" ]   && debugflags='-wd'
     [ -n "$g_profile" ] && debugflags='-wd:DProf'
 
     # Perl compiler only takes the output file as a argument
-	    
+
     [ "$1" = debug -o "$1" = trace ]  && shift;
     [ "$1" = nolock ] && shift;
-    shift 
+    shift
 
     options="--verbose=$VERBOSITY --family=6"
     [ -n "$STARTUP_LOG" ] && options="$options --log=$STARTUP_LOG"
@@ -289,6 +379,7 @@ compiler() {
     [ -n "$g_preview" ] && options="$options --preview"
     [ "$g_debugging" = trace ] && options="$options --debug"
     [ -n "$g_refreshchains" ] && options="$options --refresh=$g_refreshchains"
+    [ -n "$g_confess" ] && options="$options --confess"
     [ -x $pc ] || startup_error "Shorewall6 requires the shorewall package which is not installed"
 
     if [ -n "$PERL" ]; then
@@ -300,13 +391,14 @@ compiler() {
 	PERL=/usr/bin/perl
     fi
 
-    if [ $g_perllib != ${g_libexec}/shorewall ]; then
+    if [ $g_perllib = ${g_libexec}/shorewall ]; then
+	$PERL $debugflags $pc $options $@
+    else
 	PERL5LIB=$g_perllib
 	export PERL5LIB
+	$PERL $debugflags $pc $options $@
     fi
-    
-    $command $PERL $debugflags $pc $options $@
-}    
+}
 
 #
 # Start Command Executor
@@ -314,7 +406,7 @@ compiler() {
 start_command() {
     local finished
     finished=0
-    local restorefile
+    local object
 
     do_it() {
 	local rc
@@ -328,7 +420,7 @@ start_command() {
 	else
 	    progress_message3 "Compiling..."
 
-	    if compiler run $g_debugging $nolock compile ${VARDIR}/.start; then
+	    if compiler $g_debugging $nolock compile ${VARDIR}/.start; then
 		[ -n "$nolock" ] || mutex_on
 		run_it ${VARDIR}/.start $g_debugging start
 		rc=$?
@@ -369,6 +461,15 @@ start_command() {
 			    g_fast=Yes
 			    option=${option#f}
 			    ;;
+			p*)
+			    [ -n "$(which conntrack)" ] || fatal_error "The '-p' option requires the conntrack utility which does not appear to be installed on this system"
+			    g_purge=Yes
+			    option=${option%p}
+			    ;;
+			c*)
+			    AUTOMAKE=
+			    option=${option#c}
+			    ;;			    
 			*)
 			    usage 1
 			    ;;
@@ -405,24 +506,19 @@ start_command() {
     esac
 
     if [ -n "${g_fast}${AUTOMAKE}" ]; then
-	if qt mywhich make; then
-	    restorefile=$RESTOREFILE
-	    if [ -z "$g_fast" ]; then
-		#
-		# Autofast -- use the last compiled script
-		#
-		RESTOREFILE=firewall
-	    fi
-
-	    export RESTOREFILE
-
-	    if ! make -qf ${CONFDIR}/Makefile; then
-		g_fast=
-		AUTOMAKE=
-	    fi
-
-	    RESTOREFILE=$restorefile
+	if [ -z "$g_fast" -o -z "$LEGACY_FASTSTART" ]; then
+	    #
+	    # Automake or LEGACY_FASTSTART=No -- use the last compiled script
+	    #
+	    object=firewall
 	else
+	    #
+	    # 'start -f' with LEGACY_FASTSTART=Yes -- use last saved configuration
+	    #
+	    object=$RESTOREFILE
+	fi
+
+	if ! uptodate ${VARDIR}/$object; then
 	    g_fast=
 	    AUTOMAKE=
 	fi
@@ -454,7 +550,7 @@ compile_command() {
     finished=0
 
     while [ $finished -eq 0 ]; do
-	[ $# -eq 0 ] && break;
+	[ $# -eq 0 ] && break
 	option=$1
 	case $option in
 	    -*)
@@ -476,10 +572,14 @@ compile_command() {
 			t*)
 			    g_test=Yes
 			    option=${option#t}
-			    ;;			    
+			    ;;
 			d*)
 			    g_debug=Yes;
 			    option=${option#d}
+			    ;;
+			T*)
+			    g_confess=Yes
+			    option=${option#T}
 			    ;;
 			-)
 			    finished=1
@@ -528,7 +628,7 @@ compile_command() {
 
     [ "x$file" = x- ] || progress_message3 "Compiling..."
 
-    compiler exec $g_debugging compile $file
+    compiler $g_debugging compile $file
 }
 
 #
@@ -558,13 +658,17 @@ check_command() {
 			    g_profile=Yes
 			    option=${option#p}
 			    ;;
-			r*)
-			    g_preview=Yes;
-			    option=${option#r}
-			    ;;
 			d*)
 			    g_debug=Yes;
 			    option=${option#d}
+			    ;;
+			r*)
+			    g_preview=Yes
+			    option=${option#r}
+			    ;;
+			T*)
+			    g_confess=Yes
+			    option=${option#T}
 			    ;;
 			*)
 			    usage 1
@@ -602,7 +706,7 @@ check_command() {
 
     progress_message3 "Checking..."
 
-    compiler exec $g_debugging $nolock check
+    compiler $g_debugging $nolock check
 }
 
 #
@@ -635,6 +739,10 @@ restart_command() {
 			    g_fast=Yes
 			    option=${option#f}
 			    ;;
+			c*)
+			    AUTOMAKE=
+			    option=${option#c}
+			    ;;			    
 			n*)
 			    g_noroutes=Yes
 			    option=${option#n}
@@ -683,21 +791,13 @@ restart_command() {
     [ -n "$STARTUP_ENABLED" ] || fatal_error "Startup is disabled"
 
     if [ -z "$g_fast" -a -n "$AUTOMAKE" ]; then
-	if qt mywhich make; then
-	    #
-	    # RESTOREFILE is exported by get_config()
-	    #
-	    restorefile=$RESTOREFILE
-	    RESTOREFILE=firewall
-	    make -qf ${CONFDIR}/Makefile && g_fast=Yes
-	    RESTOREFILE=$restorefile
-	fi
+	uptodate ${VARDIR}/firewall && g_fast=Yes
     fi
 
-    if [ -z "$g_fast" ]; then  
+    if [ -z "$g_fast" ]; then
 	progress_message3 "Compiling..."
 
-	if compiler run $g_debugging $nolock compile ${VARDIR}/.restart; then
+	if compiler $g_debugging $nolock compile ${VARDIR}/.restart; then
 	    [ -n "$nolock" ] || mutex_on
 	    run_it ${VARDIR}/.restart $g_debugging restart
 	    rc=$?
@@ -767,7 +867,7 @@ refresh_command() {
 
     progress_message3 "Compiling..."
 
-    if compiler run $g_debugging $nolock compile ${VARDIR}/.refresh; then
+    if compiler $g_debugging $nolock compile ${VARDIR}/.refresh; then
 	[ -n "$nolock" ] || mutex_on
 	run_it ${VARDIR}/.refresh $g_debugging refresh
 	rc=$?
@@ -785,6 +885,7 @@ refresh_command() {
 safe_commands() {
     local finished
     finished=0
+    local command
 
     # test is the shell supports timed read
     read -t 0 junk 2> /dev/null
@@ -867,7 +968,7 @@ safe_commands() {
 
     progress_message3 "Compiling..."
 
-    if ! compiler run $g_debugging nolock compile ${VARDIR}/.$command; then
+    if ! compiler $g_debugging nolock compile ${VARDIR}/.$command; then
 	status=$?
 	exit $status
     fi
@@ -887,7 +988,7 @@ safe_commands() {
 
     [ -n "$nolock" ] || mutex_on
 
-    if run_it ${VARDIR}/.$command $command; then
+    if run_it ${VARDIR}/.$command $g_debugging $command; then
 
 	echo -n "Do you want to accept the new firewall configuration? [y/n] "
 
@@ -899,7 +1000,7 @@ safe_commands() {
 	    else
 		run_it ${VARDIR}/.$command clear
 	    fi
-	    
+
 	    [ -n "$nolock" ] || mutex_off
 
 	    echo "New configuration has been rejected and the old one restored"
@@ -930,7 +1031,7 @@ try_command() {
 		echo "Directory $1 does not exist" >&2 && exit 2
 	    fi
 	fi
-	
+
 	SHOREWALL_DIR=$(resolve_file $1)
     }
 
@@ -973,7 +1074,7 @@ try_command() {
 	2)
 	    handle_directory $1
 	    timeout=$2
-	    case $timeout in 
+	    case $timeout in
 		*[!0-9]*)
                     echo "   ERROR: Invalid timeout ($timeout)" >&2;
 		    exit 1
@@ -1003,7 +1104,7 @@ try_command() {
 
     progress_message3 "Compiling..."
 
-    if ! compiler run $g_debugging $nolock compile ${VARDIR}/.$command; then
+    if ! compiler $g_debugging $nolock compile ${VARDIR}/.$command; then
 	status=$?
 	exit $status
     fi
@@ -1025,12 +1126,12 @@ try_command() {
 
     if run_it ${VARDIR}/.$command $command && [ -n "$timeout" ]; then
 	sleep $timeout
-	    
+
 	if [ "$command" = "restart" ]; then
 	    run_it ${VARDIR}/.try restore
 	else
 	    run_it ${VARDIR}/.$command clear
-	fi	    
+	fi
     fi
 
     [ -n "$nolock" ] || mutex_off
@@ -1047,7 +1148,7 @@ rsh_command() {
 rcp_command() {
     files="$1"
     destination=$2
-    
+
     eval $RCP_COMMAND
 }
 
@@ -1073,10 +1174,8 @@ reload_command() # $* = original arguments less the command.
     getcaps=
     local root
     root=root
-    local compiler
-    compiler=
     local libexec
-    libexec=share
+    libexec=/usr/share
 
     litedir=/var/lib/shorewall6-lite
 
@@ -1135,11 +1234,20 @@ reload_command() # $* = original arguments less the command.
 
     temp=$(rsh_command /sbin/shorewall6-lite show config 2> /dev/null | grep ^LITEDIR | sed 's/LITEDIR is //')
 
-    [ -n "$temp" ] && litedir=$temp
+    [ -n "$temp" ] && litedir="$temp"
 
     temp=$(rsh_command /sbin/shorewall6-lite show config 2> /dev/null | grep ^LIBEXEC | sed 's/LIBEXEC is //')
 
-    [ -n "$temp" ] && libexec=$temp
+    if [ -n "$temp" ]; then
+	case $temp in
+	    /*)
+		libexec="$temp"
+		;;
+	    *)
+		libexec=/usr/$temp
+		;;
+	esac
+    fi
 
     if [ -z "$getcaps" ]; then
 	SHOREWALL_DIR=$(resolve_file $directory)
@@ -1154,8 +1262,10 @@ reload_command() # $* = original arguments less the command.
 	    ensure_config_path
 	fi
 
+	[ -n "$DONT_LOAD" ] && DONT_LOAD="$(echo $DONT_LOAD | tr ',' ' ')"
+
 	progress_message "Getting Capabilities on system $system..."
-	if ! rsh_command "MODULESDIR=$MODULESDIR MODULE_SUFFIX=\"$MODULE_SUFFIX\" IP6TABLES=$IP6TABLES /usr/$libexec/shorewall6-lite/shorecap" > $directory/capabilities; then
+	if ! rsh_command "MODULESDIR=$MODULESDIR MODULE_SUFFIX=\"$MODULE_SUFFIX\" IP6TABLES=$IP6TABLES DONT_LOAD=\"$DONT_LOAD\" $libexec/shorewall6-lite/shorecap" > $directory/capabilities; then
 	    fatal_error "ERROR: Capturing capabilities on system $system failed"
 	fi
     fi
@@ -1164,7 +1274,7 @@ reload_command() # $* = original arguments less the command.
 
     [ -n "$g_timestamp" ] && timestamp='-t' || timestamp=
 
-    if shorewall6 $g_debugging $verbose $timestamp compile -e $compiler $directory $directory/firewall && \
+    if shorewall6 $g_debugging $verbose $timestamp compile -e $directory $directory/firewall && \
 	progress_message3 "Copying $file and ${file}.conf to ${system}:${litedir}..." && \
 	rcp_command "$directory/firewall $directory/firewall.conf" ${litedir}
     then
@@ -1194,15 +1304,13 @@ reload_command() # $* = original arguments less the command.
 export_command() # $* = original arguments less the command.
 {
     local verbose
-    verbose=$(make_verbose) 
+    verbose=$(make_verbose)
     local file
-    file= 
+    file=
     local finished
-    finished=0 
-    local directory 
+    finished=0
+    local directory
     local target
-    local compiler
-    compiler=
 
     while [ $finished -eq 0 -a $# -gt 0 ]; do
 	option=$1
@@ -1253,7 +1361,7 @@ export_command() # $* = original arguments less the command.
 
     file=$(resolve_file $directory/firewall)
 
-    if shorewall6 $g_debugging $verbose compile -e $compiler $directory $directory/firewall && \
+    if shorewall6 $g_debugging $verbose compile -e $directory $directory/firewall && \
 	echo "Copying $file and ${file}.conf to ${target#*@}..." && \
 	scp $directory/firewall $directory/firewall.conf $target
     then
@@ -1293,11 +1401,26 @@ usage() # $1 = exit status
     echo "   reject <address> ..."
     echo "   reload [ -s ] [ -c ] [ -r <root user> ] [ <directory> ] <system>"
     echo "   reset [ <chain> ... ]"
-    echo "   restart [ -n ] [ -f ] [ <directory> ]"
+    echo "   restart [ -n ] [ -p ] [-d] [ -f ] [ -c ][ <directory> ]"
     echo "   restore [ -n ] [ <file name> ]"
     echo "   save [ <file name> ]"
-    echo "   show [ -x ] [ -m ] [-f] [ -t {filter|mangle} ] [ {chain [<chain> [ <chain> ... ]|actions|capabilities|classifiers|config|connections|filters|ip|log [<regex>]|macros|mangle|nat|policies|raw|routing|tc|vardir|zones} ]"
-    echo "   start [ -f ] [ -n ] [ <directory> ]"
+    echo "   show [ -x ] [ -t {filter|mangle|nat} ] [ {chain [<chain> [ <chain> ... ]"
+    echo "   show actions"
+    echo "   show [ -f ] capabilities"
+    echo "   show classifiers"
+    echo "   show config"
+    echo "   show connections"
+    echo "   show filters"
+    echo "   show ip"
+    echo "   show [ -m ] log [<regex>]"
+    echo "   show macro <macro>"
+    echo "   show macros"
+    echo "   show [ -x ] mangle|raw|routing"
+    echo "   show policies"
+    echo "   show tc [ device ]"
+    echo "   show vardir"
+    echo "   show zones"
+    echo "   start [ -f ] [ -n ] [ -p ] [ -c ] [ <directory> ]"
     echo "   stop"
     echo "   status"
     echo "   try <directory> [ <timeout> ]"
@@ -1313,6 +1436,7 @@ version_command() {
     finished=0
     local all
     all=
+    local product
 
     while [ $finished -eq 0 -a $# -gt 0 ]; do
 	option=$1
@@ -1374,6 +1498,9 @@ if [ $# -gt 0 ] && [ "$1" = "nolock" ]; then
 fi
 
 SHOREWALL_DIR=
+g_noroutes=
+g_purge=
+
 g_ipt_options="-nv"
 g_fast=
 g_verbose_offset=0
@@ -1381,10 +1508,7 @@ g_use_verbosity=
 g_debug=
 g_export=
 g_refreshchains=:none:
-
-g_noroutes=
-g_purge=
-g_timestamp=
+g_confess=
 
 #
 # Make sure that these variables are cleared
@@ -1439,7 +1563,7 @@ while [ $finished -eq 0 ]; do
 			;;
 		    v*)
 			option=${option#v}
-			case $option in 
+			case $option in
 			    -1*)
 				g_use_verbosity=-1
 				option=${option#-1}
@@ -1498,8 +1622,9 @@ SHAREDIR=/usr/share/shorewall6
 CONFDIR=/etc/shorewall6
 g_product="Shorewall6"
 g_recovering=
-g_libexec=share
-g_perllib=share/shorewall
+g_timestamp=
+g_libexec=/usr/share
+g_perllib=/usr/share/shorewall
 
 [ -f ${CONFDIR}/vardir ] && . ${CONFDIR}/vardir
 
@@ -1657,6 +1782,11 @@ case "$COMMAND" in
 	[ -n "$g_debugging" ] && set -x
 	[ $# -eq 1 ] && usage 1
 	if shorewall6_is_started ; then
+	    if ! chain_exists dynamic; then
+		echo "Dynamic blacklisting is not supported in the current $g_product configuration"
+		exit 2
+	    fi
+
 	    [ -n "$nolock" ] || mutex_on
 	    block DROP Dropped $*
 	    [ -n "$nolock" ] || mutex_off
@@ -1669,6 +1799,11 @@ case "$COMMAND" in
 	[ -n "$g_debugging" ] && set -x
 	[ $# -eq 1 ] && usage 1
 	if shorewall6_is_started ; then
+	    if ! chain_exists dynamic; then
+		echo "Dynamic blacklisting is not supported in the current $g_product configuration"
+		exit 2
+	    fi
+
 	    [ -n "$nolock" ] || mutex_on
 	    block logdrop Dropped $*
 	    [ -n "$nolock" ] || mutex_off
@@ -1737,14 +1872,9 @@ case "$COMMAND" in
 	g_restorepath=${VARDIR}/$RESTOREFILE
 
 	if [ -x $g_restorepath ]; then
-
-	    if [ -x ${g_restorepath}-ipsets ]; then
-		rm -f ${g_restorepath}-ipsets
-		echo "    ${g_restorepath}-ipsets removed"
-	    fi
-
 	    rm -f $g_restorepath
 	    rm -f ${g_restorepath}-iptables
+	    rm -f ${g_restorepath}-ipsets
 	    echo "    $g_restorepath removed"
 	elif [ -f $g_restorepath ]; then
 	    echo "   $g_restorepath exists and is not a saved Shorewall6 configuration"
@@ -1783,7 +1913,7 @@ case "$COMMAND" in
 	else
 	    fatal_error "Shorewall6 is not started"
 	fi
-	;;	
+	;;
      noiptrace)
 	get_config
 	shift
@@ -1793,7 +1923,8 @@ case "$COMMAND" in
 	else
 	    fatal_error "Shorewall6 is not started"
 	fi
-	;;	    *)
+	;;
+    *)
 	usage 1
 	;;
 
